Changing the enviroment to dev

diff --git a/.github/workflows/infrastructure.yaml b/.github/workflows/infrastructure.yaml
--- a/.github/workflows/infrastructure.yaml
+++ b/.github/workflows/infrastructure.yaml
@@ -46,7 +46,7 @@ jobs:
 
   package-lambdas:
     name: Package Lambda Functions seventh  attempt
-    needs: data
+    needs: datagit
 
     runs-on: ubuntu-latest
 
@@ -160,6 +160,40 @@ jobs:
       tags_file: cloudformation/config/tags.json
       environment: ${{ vars.DEPLOY_ENV }}
     secrets: inherit
+  db-init:
+    name: Initialize Database
+    needs: application
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Configure AWS credentials via OIDC
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        role-to-assume: ${{ vars.AWS_ROLE_ARN }}
+        aws-region: ${{ vars.AWS_REGION }}
+
+    - name: Run DB Init Lambda
+      run: |
+        FUNCTION_NAME="cloudmart-${{ vars.DEPLOY_ENV }}-dbInit-lambda"
+
+        echo "Invoking DB Init Lambda: $FUNCTION_NAME"
+
+        aws lambda invoke \
+          --function-name "$FUNCTION_NAME" \
+          --invocation-type RequestResponse \
+          --payload '{}' \
+          response.json
+
+        cat response.json
+
+    - name: Check DB Init Result
+      run: |
+        if grep -q '"statusCode": 500' response.json; then
+          echo "Database initialization failed"
+          exit 1
+        fi
+
+        echo "Database initialization completed successfully"
   monitoring:
     name: Deploy Monitoring  Stack check yes
     needs: application
